### ISSUE TITLE
If there is no census data, the Geocoder should return an empty list

### ISSUE THREAD

**Issue by jlorentson** [imsweb/naaccr-geocoder-client#14]
Testing in SEER\*DMS, @criderp ran into a situation where a bad street address resulted in the Geocoder returning an empty Map of census results. (This caused NullPointerException in SEER*DMS, though that problem has been fixed.) It was suggested that, in the event that there is no census data to return, the Geocoder should return just an empty `List<GeocodeOutput>.` In that case, we would not have any of the information the Geocoder would return for a bad address, including the URL.

@ctmay4 what are your thoughts on this?

**Comment by criderp** [comment]
I was looking at this again and realized I made a mistake in my testing.  I made some geocoder calls and it returned nothing, but that was only because I forgot to add the API key to the URL. It didn't bother to tell me there was a problem, it just didn't return anything!

I do think it make sense to return an empty collection if there are no results, but I don't think that case will ever actually happen. So, I don't think we should change anything.
